<?php
/**
* @file
* Forcontu Hello module file.
*/

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\taxonomy\Entity\Term;

/**
* Implements hook_help().
*/

function forcontu_hello_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {

switch ($route_name) {
  case 'help.page.forcontu_hello':
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('This module shows how to create a simple page. ') . '</p>';
    return $output;
  case 'forcontu_hello.hello':
    $output = '';
    $output .= '<p>' . t('This is a very simple page created by the Forcontu Hello module. ') . '</p>';
    return $output;
  }
}

/**
 * Implements hook_install().
 */

function forcontu_hello_install(){

  \Drupal::state()->set('forcontu_hello.test', TRUE);

  $term = Term::create(array(
    'name' => t('Forcontu Hello'),
    'vid' => 'tags',
  ));
  $term->save();
}

/**
 * Implements hook_uninstall().
 */

function forcontu_hello_uninstall(){

  \Drupal::state()->delete('forcontu_hello.test');

}



